name: npm publish

# 发布版本触发
on:
  push:
    tags:
      - v*
      
permissions:
  contents: write
  id-token: write  # Required for OIDC

jobs:
  publish:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22.x
          registry-url: 'https://registry.npmjs.org/'
          # 关键配置：启用 OIDC
          always-auth: true

      - name: npm i
        run: |
          npm i
      
      - name: npm build
        run: |
          npm run build

      - name: Install dependencies
        run: npm ci
          
      - name: npm publish
        run: |
          cd ./dist
          npm publish -r --tag latest --no-git-checks

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
        
