name: npm publish

# 发布版本触发
on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: write   # 写权限用于创建 GitHub Release
  id-token: write   # Required for OIDC

jobs:
  publish:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: npm build
        run: pnpm build

      - name: npm publish
        working-directory: ./dist
        run: pnpm publish --tag latest --no-git-checks --access public

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            dist/
